name: Main

on:
  push:
    branches: [main]
  schedule:
    - cron: "0 8,20 * * *"

jobs:
  unit-tests:
    name: Unit tests
    uses: apple/swift-nio/.github/workflows/unit_tests.yml@main
    with:
      linux_5_9_enabled: false
      linux_5_10_enabled: false
      linux_6_0_arguments_override: "--explicit-target-dependency-import-check error -Xswiftc -warnings-as-errors -Xswiftc -require-explicit-availability"
      linux_6_1_arguments_override: "--explicit-target-dependency-import-check error -Xswiftc -warnings-as-errors -Xswiftc -require-explicit-availability"
      linux_nightly_next_arguments_override: "--explicit-target-dependency-import-check error -Xswiftc -require-explicit-availability"
      linux_nightly_main_arguments_override: "--explicit-target-dependency-import-check error -Xswiftc -require-explicit-availability"

  construct-plugin-tests-matrix:
    name: Construct plugin tests matrix
    runs-on: ubuntu-latest
    outputs:
      plugin-tests-matrix: '${{ steps.generate-matrix.outputs.plugin-tests-matrix }}'
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
        with:
          persist-credentials: false
      - id: generate-matrix
        run: echo "plugin-tests-matrix=$(curl -s https://raw.githubusercontent.com/apple/swift-nio/main/scripts/generate_matrix.sh | bash)" >> "$GITHUB_OUTPUT"
        env:
          MATRIX_LINUX_5_9_ENABLED: false
          MATRIX_LINUX_5_10_ENABLED: false
          MATRIX_LINUX_COMMAND: "./dev/plugin-tests.sh"
          MATRIX_LINUX_SETUP_COMMAND: "apt-get update -y -q && apt-get install -y -q curl protobuf-compiler"

  plugin-tests-matrix:
    name: Plugin tests
    needs: construct-plugin-tests-matrix
    uses: apple/swift-nio/.github/workflows/swift_test_matrix.yml@main
    with:
      name: "Plugin tests"
      matrix_string: '${{ needs.construct-plugin-tests-matrix.outputs.plugin-tests-matrix }}'

  static-sdk:
    name: Static SDK
    uses: apple/swift-nio/.github/workflows/static_sdk.yml@main
