name: Main

on:
  push:
    branches: [main]
  schedule:
    - cron: "0 8,20 * * *"

jobs:
  unit-tests:
    name: Unit tests
    uses: apple/swift-nio/.github/workflows/unit_tests.yml@main
    with:
      linux_5_9_enabled: false
      linux_5_10_enabled: false
      linux_6_0_arguments_override: "--explicit-target-dependency-import-check error -Xswiftc -require-explicit-sendable"
      linux_nightly_6_0_arguments_override: "--explicit-target-dependency-import-check error -Xswiftc -require-explicit-sendable"
      linux_nightly_main_arguments_override: "--explicit-target-dependency-import-check error -Xswiftc -require-explicit-sendable"

  plugin-tests:
    name: Plugin tests
    uses: apple/swift-nio/.github/workflows/swift_load_test_matrix.yml@main
    with:
      name: "Plugin tests"
      matrix_path: ".github/workflows/matrices/plugin-tests.json"
